# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-16 23:36


import basic_models.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('base_template', models.CharField(blank=True, help_text=b"If present, the name of a django template.<br/> The body field will be present as the 'email_body' context variable", max_length=1024)),
                ('subject', models.CharField(max_length=1024)),
                ('from_address', models.CharField(blank=True, help_text=b"Specify as: 'Full Name &lt;email@address>'<br/>Defaults to: 'no-reply@site.domain'", max_length=1024, null=True)),
                ('body', models.TextField(default=b'')),
                ('txt_body', models.TextField(blank=True, help_text=b'If present, use as the plain-text body', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(basic_models.models.NaturalKey, models.Model),
        ),
    ]
