# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-17 22:31


import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True),
        ),
    ]
