# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:52


import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplates', '0005_auto_20171005_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True),
        ),
    ]
